
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

logger:
  default: warning
  logs:
    homeassistant.core: warning
    homeassistant.loader: warning
    homeassistant.config: warning
    asyncio: warning
    custom_components.generic_smart_thermostat: debug

schedule_list:

shopping_list:

input_boolean:
  testswitch:
    name: Test Boolean
    initial: off
  testswitch2:
    name: Test Boolean 2
    initial: off

input_number:
  temp_in:
    min: -20
    max: 35
    step: 0.1
    mode: box
  temp_out:
    min: -20
    max: 35
    step: 0.1
    mode: box

sensor:
  - platform: template
    sensors:
      temp_in:
        value_template: "{{ states('input_number.temp_in') }}"
      temp_out:
        value_template: "{{ states('input_number.temp_out') }}"

switch:
 - platform: template
   switches:
    testswitch:
       value_template: "{{ is_state('input_boolean.testswitch', 'on') }}"
       turn_on:
         service: input_boolean.turn_on
         entity_id: input_boolean.testswitch
       turn_off:
         service: input_boolean.turn_off
         entity_id: input_boolean.testswitch
    testswitch2:
       value_template: "{{ is_state('input_boolean.testswitch2', 'on') }}"
       turn_on:
         service: input_boolean.turn_on
         entity_id: input_boolean.testswitch2
       turn_off:
         service: input_boolean.turn_off
         entity_id: input_boolean.testswitch2


climate:
  - platform: generic_smart_thermostat
    name: Smart thermo dev
    heater: switch.testswitch
    in_temp_sensor: sensor.temp_in
    out_temp_sensor: sensor.temp_out
    calculate_period: 1
    preheat: true
    schedule:
      - mode: "eco"
        start: "07:30"
        days: "0-6"
      - mode: "comfort"
        days: "0-6"
        start: "23:18"
      - mode: "eco"
        days: "0-6"
        start: "23:20"

  - platform: generic_thermostat
    name: default thermo
    heater: switch.testswitch2
    target_sensor: sensor.temp_in
    away_temp: 15
    min_cycle_duration:
      seconds: 5

